// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6TJ5zmONsbR09pLNZUVJlMycZ4Zm0hlE',
    appId: '1:464369909664:web:4eabaf6e2185eaf0302ec5',
    messagingSenderId: '464369909664',
    projectId: 'chat-bro-603f3',
    authDomain: 'chat-bro-603f3.firebaseapp.com',
    storageBucket: 'chat-bro-603f3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0oYFqfR1XMaskugZKlEDClT5oe4kYUMI',
    appId: '1:464369909664:android:e39fa33da65fde6e302ec5',
    messagingSenderId: '464369909664',
    projectId: 'chat-bro-603f3',
    storageBucket: 'chat-bro-603f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxDDWHkVHauDt37zkqWFZgDkC3weoeQTM',
    appId: '1:464369909664:ios:64c96b86b078cfc5302ec5',
    messagingSenderId: '464369909664',
    projectId: 'chat-bro-603f3',
    storageBucket: 'chat-bro-603f3.appspot.com',
    iosBundleId: 'com.example.messagerChat1',
  );
}
